vundle:
	@mkdir -p ~/tmp
	@echo "Cloning Vundle..."
	@git clone git://github.com/gmarik/vundle.git bundle/vundle > /dev/null
plugins:
	@echo "Cloning plug-ins..."
	@vim +BundleInstall +qall
	@echo "Done."
